# Assign a unique port (8082) so it runs alongside Product Service (8081)
server.port=8082

# Service Identity
spring.application.name=order-service

# Database Connection Details (Pointing to the Order DB)
spring.datasource.url=jdbc:mysql://localhost:3306/jumbosix_order_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sidhant@123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Connect to Eureka Discovery Phone Book
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Location of the running local Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Serializer classes for keys and values sent to the broker
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer