# Standard port for Eureka Discovery Server
server.port=8761

# Prevent Eureka from trying to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Give this utility application a unique spring identity
spring.application.name=jumbosix-discovery-server