# Assign a unique port (8084)
server.port=8084

# Service Identity
spring.application.name=notification-service

# Connect to Eureka Discovery Registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Location of the running local Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Unique Consumer Group Identity for Notifications
spring.kafka.consumer.group-id=notification-group

# Offset and Deserializers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer